name             'sprout-osx-base'
maintainer       'Pivotal Labs'
maintainer_email 'accounts@pivotallabs.com'
license          'MIT'
description      'A handful of things every Sprout recipe needs'
long_description 'A handful of things every Sprout recipe needs'
version          '0.1.0'
supports         'mac_os_x'
