name             'sprout-osx-settings'
maintainer       'Pivotal Labs'
maintainer_email 'accounts@pivotallabs.com'
license          'MIT'
description      'Recipes to configure various aspects of OS X'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-osx-base'
depends          'osx'
